import type { ActivityTag, CanonicalMood, Track, TrackLocale, WeatherTag } from "./types.js";

type TrackSeed = readonly [
  id: string,
  title: string,
  artist: string,
  year: number,
  locale: TrackLocale,
  instrumental: boolean,
  durationSec: number,
  energy: number,
  valence: number,
  acousticness: number,
  familiarity: number,
  moods: readonly CanonicalMood[],
  weather: readonly WeatherTag[],
  activities: readonly ActivityTag[]
];

const seeds: readonly TrackSeed[] = [
  ["iu-through-the-night", "Through the Night", "IU", 2017, "ko", false, 253, .24, .48, .84, .92, ["calm", "lonely", "romantic"], ["rain", "cloudy", "cold"], ["rest", "sleep"]],
  ["iu-palette", "Palette", "IU", 2017, "ko", false, 217, .52, .72, .42, .92, ["content", "hopeful"], ["clear", "cloudy"], ["walk", "commute"]],
  ["iu-blueming", "Blueming", "IU", 2019, "ko", false, 217, .78, .86, .18, .94, ["joyful", "energetic", "romantic"], ["clear"], ["walk", "commute", "exercise"]],
  ["iu-eight", "eight", "IU", 2020, "ko", false, 168, .72, .68, .24, .95, ["hopeful", "joyful"], ["clear", "wind"], ["walk", "commute"]],
  ["iu-love-wins-all", "Love wins all", "IU", 2024, "ko", false, 271, .42, .42, .72, .93, ["sad", "hopeful", "romantic"], ["rain", "snow", "cold"], ["rest"]],
  ["bts-spring-day", "Spring Day", "BTS", 2017, "ko", false, 274, .58, .52, .45, .98, ["lonely", "hopeful"], ["cloudy", "cold", "wind"], ["walk", "commute"]],
  ["bts-dynamite", "Dynamite", "BTS", 2020, "international", false, 199, .88, .92, .10, .99, ["joyful", "energetic"], ["clear", "hot"], ["exercise", "commute"]],
  ["bts-life-goes-on", "Life Goes On", "BTS", 2020, "ko", false, 207, .44, .66, .58, .96, ["calm", "content", "hopeful"], ["cloudy", "rain"], ["rest", "work"]],
  ["bts-mikrokosmos", "Mikrokosmos", "BTS", 2019, "ko", false, 224, .75, .82, .20, .95, ["hopeful", "joyful"], ["clear"], ["walk", "commute"]],
  ["akmu-heartbreak", "How can I love the heartbreak, you're the one I love", "AKMU", 2019, "ko", false, 290, .20, .17, .82, .90, ["sad", "lonely"], ["rain", "cloudy", "cold"], ["rest"]],
  ["akmu-200-percent", "200%", "AKMU", 2014, "ko", false, 193, .72, .90, .34, .91, ["joyful", "romantic"], ["clear"], ["walk", "commute"]],
  ["akmu-dinosaur", "DINOSAUR", "AKMU", 2017, "ko", false, 240, .69, .56, .24, .86, ["anxious", "hopeful"], ["wind", "cloudy"], ["walk", "commute"]],
  ["taeyeon-11-11", "11:11", "TAEYEON", 2016, "ko", false, 223, .27, .43, .84, .91, ["calm", "lonely", "romantic"], ["rain", "cold"], ["rest", "sleep"]],
  ["taeyeon-weekend", "Weekend", "TAEYEON", 2021, "ko", false, 233, .66, .86, .24, .92, ["content", "joyful"], ["clear", "hot"], ["walk", "commute"]],
  ["taeyeon-invu", "INVU", "TAEYEON", 2022, "ko", false, 205, .62, .35, .20, .92, ["sad", "romantic"], ["cloudy", "wind"], ["commute"]],
  ["newjeans-ditto", "Ditto", "NewJeans", 2022, "ko", false, 186, .52, .55, .46, .98, ["lonely", "romantic", "content"], ["snow", "cloudy", "cold"], ["walk", "commute"]],
  ["newjeans-super-shy", "Super Shy", "NewJeans", 2023, "ko", false, 154, .84, .91, .11, .98, ["joyful", "energetic", "romantic"], ["clear", "hot"], ["exercise", "walk"]],
  ["newjeans-hype-boy", "Hype Boy", "NewJeans", 2022, "ko", false, 180, .82, .88, .10, .99, ["joyful", "energetic"], ["clear", "hot"], ["exercise", "commute"]],
  ["day6-time-of-our-life", "Time of Our Life", "DAY6", 2019, "ko", false, 205, .92, .90, .07, .92, ["hopeful", "joyful", "energetic"], ["clear", "wind"], ["exercise", "commute"]],
  ["day6-you-were-beautiful", "You Were Beautiful", "DAY6", 2017, "ko", false, 283, .64, .30, .30, .94, ["sad", "lonely", "romantic"], ["rain", "cloudy"], ["commute", "rest"]],
  ["red-velvet-feel-my-rhythm", "Feel My Rhythm", "Red Velvet", 2022, "ko", false, 210, .76, .85, .18, .91, ["joyful", "energetic"], ["clear"], ["walk", "exercise"]],
  ["red-velvet-psycho", "Psycho", "Red Velvet", 2019, "ko", false, 211, .65, .34, .22, .95, ["anxious", "romantic"], ["cloudy", "wind"], ["commute"]],
  ["seventeen-world", "_WORLD", "SEVENTEEN", 2022, "ko", false, 178, .74, .88, .16, .91, ["content", "joyful"], ["clear", "hot"], ["walk", "commute"]],
  ["seventeen-very-nice", "VERY NICE", "SEVENTEEN", 2016, "ko", false, 192, .96, .94, .05, .94, ["joyful", "energetic"], ["clear"], ["exercise"]],
  ["lesserafim-perfect-night", "Perfect Night", "LE SSERAFIM", 2023, "international", false, 159, .67, .83, .18, .94, ["content", "joyful"], ["clear", "cloudy"], ["walk", "commute"]],
  ["adele-someone-like-you", "Someone Like You", "Adele", 2011, "international", false, 285, .20, .16, .88, .99, ["sad", "lonely"], ["rain", "cloudy", "cold"], ["rest"]],
  ["adele-easy-on-me", "Easy On Me", "Adele", 2021, "international", false, 224, .30, .30, .78, .97, ["sad", "hopeful"], ["rain", "cloudy"], ["rest"]],
  ["coldplay-fix-you", "Fix You", "Coldplay", 2005, "international", false, 295, .48, .42, .60, .99, ["sad", "hopeful"], ["rain", "cold"], ["rest", "walk"]],
  ["coldplay-adventure-lifetime", "Adventure of a Lifetime", "Coldplay", 2015, "international", false, 264, .86, .90, .10, .96, ["joyful", "energetic"], ["clear", "hot"], ["exercise", "walk"]],
  ["coldplay-yellow", "Yellow", "Coldplay", 2000, "international", false, 269, .52, .70, .45, .99, ["hopeful", "romantic"], ["clear", "cloudy"], ["walk", "rest"]],
  ["coldplay-viva-la-vida", "Viva La Vida", "Coldplay", 2008, "international", false, 242, .82, .74, .16, .99, ["hopeful", "energetic"], ["clear", "wind"], ["exercise", "commute"]],
  ["taylor-cardigan", "cardigan", "Taylor Swift", 2020, "international", false, 240, .34, .31, .73, .97, ["sad", "lonely", "romantic"], ["rain", "cloudy", "cold"], ["rest", "study"]],
  ["taylor-shake-it-off", "Shake It Off", "Taylor Swift", 2014, "international", false, 219, .91, .94, .06, .99, ["joyful", "energetic"], ["clear", "hot"], ["exercise"]],
  ["taylor-august", "august", "Taylor Swift", 2020, "international", false, 261, .58, .48, .48, .96, ["lonely", "romantic", "hopeful"], ["rain", "wind"], ["walk", "rest"]],
  ["dua-levitating", "Levitating", "Dua Lipa", 2020, "international", false, 203, .88, .92, .08, .98, ["joyful", "energetic"], ["clear", "hot"], ["exercise", "commute"]],
  ["dua-dont-start-now", "Don't Start Now", "Dua Lipa", 2019, "international", false, 183, .90, .84, .05, .98, ["joyful", "energetic"], ["clear", "hot"], ["exercise"]],
  ["pharrell-happy", "Happy", "Pharrell Williams", 2013, "international", false, 233, .86, .98, .16, .99, ["joyful", "energetic"], ["clear", "hot"], ["exercise", "commute"]],
  ["billie-ocean-eyes", "ocean eyes", "Billie Eilish", 2016, "international", false, 200, .18, .30, .82, .97, ["calm", "lonely", "romantic"], ["rain", "cloudy"], ["rest", "sleep"]],
  ["billie-lovely", "lovely", "Billie Eilish & Khalid", 2018, "international", false, 200, .24, .18, .78, .98, ["sad", "anxious", "lonely"], ["rain", "cold"], ["rest"]],
  ["billie-birds-feather", "BIRDS OF A FEATHER", "Billie Eilish", 2024, "international", false, 210, .60, .75, .32, .96, ["hopeful", "romantic"], ["clear", "cloudy"], ["walk", "commute"]],
  ["harry-as-it-was", "As It Was", "Harry Styles", 2022, "international", false, 167, .79, .66, .12, .99, ["lonely", "hopeful", "energetic"], ["clear", "wind"], ["commute", "exercise"]],
  ["harry-golden", "Golden", "Harry Styles", 2019, "international", false, 209, .78, .90, .15, .95, ["hopeful", "joyful"], ["clear", "hot"], ["walk", "commute"]],
  ["weeknd-blinding-lights", "Blinding Lights", "The Weeknd", 2019, "international", false, 200, .92, .82, .04, .99, ["energetic", "joyful"], ["clear", "cold"], ["exercise", "commute"]],
  ["ed-photograph", "Photograph", "Ed Sheeran", 2014, "international", false, 259, .31, .54, .79, .99, ["calm", "romantic", "lonely"], ["rain", "cloudy"], ["rest"]],
  ["ed-shape-of-you", "Shape of You", "Ed Sheeran", 2017, "international", false, 234, .84, .86, .12, .99, ["joyful", "energetic", "romantic"], ["clear", "hot"], ["exercise", "commute"]],
  ["lizzo-about-damn-time", "About Damn Time", "Lizzo", 2022, "international", false, 192, .91, .93, .05, .94, ["joyful", "energetic"], ["clear", "hot"], ["exercise"]],
  ["bruno-just-the-way", "Just the Way You Are", "Bruno Mars", 2010, "international", false, 221, .65, .85, .28, .99, ["joyful", "romantic"], ["clear"], ["walk", "commute"]],
  ["bruno-treasure", "Treasure", "Bruno Mars", 2012, "international", false, 179, .90, .94, .08, .98, ["joyful", "energetic"], ["clear", "hot"], ["exercise"]],
  ["sia-unstoppable", "Unstoppable", "Sia", 2016, "international", false, 217, .86, .71, .12, .96, ["hopeful", "energetic"], ["wind", "clear"], ["exercise", "commute"]],
  ["onerepublic-aint-worried", "I Ain't Worried", "OneRepublic", 2022, "international", false, 148, .86, .95, .08, .97, ["joyful", "energetic"], ["clear", "hot"], ["exercise", "walk"]],
  ["yiruma-river-flows", "River Flows in You", "Yiruma", 2001, "instrumental", true, 187, .18, .48, .94, .98, ["calm", "romantic", "focused"], ["rain", "cloudy", "cold"], ["study", "sleep", "rest"]],
  ["yiruma-kiss-the-rain", "Kiss the Rain", "Yiruma", 2003, "instrumental", true, 260, .16, .34, .96, .96, ["calm", "sad", "lonely"], ["rain", "cloudy"], ["study", "sleep", "rest"]],
  ["hisaishi-one-summers-day", "One Summer's Day", "Joe Hisaishi", 2001, "instrumental", true, 189, .22, .58, .90, .96, ["calm", "hopeful", "focused"], ["clear", "cloudy"], ["study", "rest"]],
  ["hisaishi-merry-go-round", "Merry-Go-Round of Life", "Joe Hisaishi", 2004, "instrumental", true, 311, .48, .72, .74, .97, ["hopeful", "joyful", "romantic"], ["wind", "clear"], ["study", "walk"]],
  ["einaudi-nuvole-bianche", "Nuvole Bianche", "Ludovico Einaudi", 2004, "instrumental", true, 357, .20, .38, .93, .94, ["calm", "sad", "hopeful"], ["rain", "cloudy", "cold"], ["study", "rest"]],
  ["einaudi-experience", "Experience", "Ludovico Einaudi", 2013, "instrumental", true, 315, .62, .62, .66, .94, ["focused", "hopeful", "energetic"], ["wind", "cloudy"], ["study", "work", "walk"]],
  ["arnalds-near-light", "Near Light", "Ólafur Arnalds", 2011, "instrumental", true, 208, .24, .42, .88, .68, ["calm", "focused", "hopeful"], ["snow", "cold", "cloudy"], ["study", "work", "rest"]],
  ["nils-frahm-ambre", "Ambre", "Nils Frahm", 2009, "instrumental", true, 227, .10, .40, .98, .62, ["calm", "focused", "tired"], ["rain", "snow", "cloudy"], ["study", "sleep"]],
  ["max-richter-daylight", "On the Nature of Daylight", "Max Richter", 2004, "instrumental", true, 371, .25, .22, .86, .90, ["sad", "lonely", "hopeful"], ["rain", "cloudy", "cold"], ["rest", "study"]],
  ["debussy-clair-de-lune", "Clair de Lune", "Claude Debussy", 1905, "instrumental", true, 300, .12, .45, .98, .96, ["calm", "romantic", "focused"], ["rain", "cloudy"], ["sleep", "study", "rest"]],
  ["satie-gymnopedie-one", "Gymnopédie No. 1", "Erik Satie", 1888, "instrumental", true, 210, .08, .34, .99, .91, ["calm", "tired", "lonely"], ["rain", "snow", "cloudy"], ["sleep", "study"]],
  ["chopin-nocturne-op9-no2", "Nocturne in E-flat Major, Op. 9 No. 2", "Frédéric Chopin", 1832, "instrumental", true, 270, .14, .44, .97, .95, ["calm", "romantic", "lonely"], ["rain", "cold"], ["sleep", "study", "rest"]],
  ["aphex-twin-avril-14th", "Avril 14th", "Aphex Twin", 2001, "instrumental", true, 126, .18, .52, .95, .88, ["calm", "focused", "hopeful"], ["rain", "cloudy"], ["study", "rest"]],
  ["cinematic-arrival-birds", "Arrival of the Birds", "The Cinematic Orchestra", 2008, "instrumental", true, 157, .49, .70, .71, .77, ["hopeful", "calm", "focused"], ["clear", "wind"], ["walk", "study", "rest"]],
  ["tycho-awake", "Awake", "Tycho", 2014, "instrumental", true, 283, .62, .74, .34, .82, ["focused", "hopeful", "content"], ["clear", "wind"], ["work", "study", "walk"]],
  ["bonobo-cirrus", "Cirrus", "Bonobo", 2013, "instrumental", true, 352, .68, .60, .28, .78, ["focused", "energetic"], ["cloudy", "wind"], ["work", "exercise"]],
  ["explosions-your-hand", "Your Hand in Mine", "Explosions in the Sky", 2003, "instrumental", true, 489, .58, .57, .48, .80, ["hopeful", "focused", "lonely"], ["cloudy", "wind"], ["work", "walk"]]
];

export const TRACK_CATALOG: readonly Track[] = Object.freeze(seeds.map((seed) => {
  const [id, title, artist, year, locale, instrumental, durationSec, energy, valence, acousticness, familiarity, moods, weather, activities] = seed;
  return Object.freeze({ id, title, artist, year, locale, instrumental, durationSec, energy, valence, acousticness, familiarity, moods, weather, activities });
}));

export const TRACK_BY_ID: ReadonlyMap<string, Track> = new Map(TRACK_CATALOG.map((track) => [track.id, track]));
